Adds Office world
Ekumen-OS/andino_gz pull request #58
Opened 2024-06-18 16:30 UTC by Voldivh

# 🎉 New Map

## Summary
This PR adds a new world to the simulation (Office).

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)

2024-06-19 02:55 UTC, francocipollone commented
@Voldivh I just pushed some env hooks for hooking the IGN_RESOURCE_PATH env var so the models can be found

2024-06-19 02:59 UTC, francocipollone requested changes
Note that model and world need to be migrated to Gazebo non-classic.
I will see if I can help you out with that.

2024-06-19 02:59 UTC, francocipollone commented on andino_gz/models/magazino_hallway.stl
I think that this is for other kind of world: Magazino's dataset like

2024-06-19 02:59 UTC, francocipollone commented on andino_gz/worlds/office.world
for consistency, name it at office.sdf

2024-06-19 02:59 UTC, francocipollone commented on andino_gz/worlds/office.world
> +          </material>
script materials aren't supported in the Gazebo non classic

2024-06-19 02:59 UTC, francocipollone commented on andino_gz/models/office/model.sdf
> +          </script>
script material can't be used in this gazebo version

2024-06-25 20:12 UTC, Voldivh commented
@francocipollone Just updated the world, I think the current state works for our purpose on the andino+rmf project and improvements on this map textures and the general world can be addressed on a follow up PR. This is how it looks like atm: 
![image](https://github.com/Ekumen-OS/andino_gz/assets/51831786/fbc5c9d3-59b4-4a41-a6a6-9f8f1b0416bd)

2024-06-27 16:38 UTC, francocipollone approved these changes
Merging to unblock you.

Pendings:
 - https://github.com/Ekumen-OS/andino_gz/issues/59
 - https://github.com/Ekumen-OS/andino_gz/issues/60

2024-06-27 16:39 UTC, merged