[WIP] 2nd iteration on improving office world
Ekumen-OS/andino_gz pull request #84
Opened 2024-09-10 16:03 UTC by larodriguez22

# 🎉 New feature

Closes #<NUMBER>

## Summary
Closes #81 

- Add basic roof: Normals of the mesh pointing down would allow us to see it from above in the sim
- Add correct lightning. There is no need for visual lamp assets for the first iteration of it.
        -  Office Assets
        -  Doors
        -  Windows
        - How to solve transparency.
        -  Office stuff
              - Tvs , chairs,
              - Frames

## Videos
(Only roof for now)

[Screencast from 09-10-2024 10:51:11 AM.webm](https://github.com/user-attachments/assets/e2240246-8ec4-4468-81cc-b20ee8200083)

2024-09-17 08:28 UTC, JesusSilvaUtrera commented
@larodriguez22 be careful with the DCO when you push commits, because it will give you a lot of headaches later jajaja, you can use `--signoff` whenever you do a commit to solve that. If you have problems, check the `Details` information given by Github to solve the DCO issues.

2024-11-12 16:24 UTC, larodriguez22 commented
New updates:
![Screenshot from 2024-11-12 11-16-04](https://github.com/user-attachments/assets/c20664ff-166e-4f4e-b64e-380e2931e17d)

- Roof was updated with different material
- Lights were added
- Door was added
- Windows were added with transparency
![Screenshot from 2024-11-12 11-16-55](https://github.com/user-attachments/assets/da45c9bb-a3d4-4982-bac1-112c09b2f695)
![Screenshot from 2024-11-12 11-17-34](https://github.com/user-attachments/assets/2b4e8f38-919c-4e19-8ca9-e17aa3535b43)

- Logo was added
![Screenshot from 2024-11-12 11-15-26](https://github.com/user-attachments/assets/b72b3e3d-60c4-4d92-8186-a1dc3329cf93)

2025-02-03 18:33 UTC, larodriguez22 commented
New updates: fixing lights (Less intensity, Wider angle, Distributed more uniformly)

![image](https://github.com/user-attachments/assets/7fc12b08-5322-4e2d-bfa5-87f3350ce21c)
![image](https://github.com/user-attachments/assets/3d696332-7a31-464e-af72-f1f8cbb95517)
![image](https://github.com/user-attachments/assets/d6a6d727-0be8-4101-b815-77a1bf21d4d2)

2025-02-10 19:16 UTC, larodriguez22 commented
New updates:
- New texture to the roof (maybe it needs to be more tiled?)

![Screenshot from 2025-02-10 14-09-22](https://github.com/user-attachments/assets/9fac02fc-0df7-47d4-992f-3e3ec9cd798b)

2025-03-13 16:30 UTC, IDavGal commented
Hey Lau! Sorry for the delay, I kinda lost track of this. 

I do think the ceiling texture should be more tiled, It's hard to find a sweet sport for such a big plane..
As other minor issue, I'm getting some glitchy visual effect on the logo and the frame. I suggest using the [`<render_order>`](http://sdformat.org/spec?ver=1.12&elem=material#material_render_order) tag in the frame material, set to a value >0.

Other than that, the windows and lighting look really good.

2025-09-11 18:13 UTC, IDavGal approved these changes
Looks great Lau. One small thing, can we use a different texture for the doors, or at least rotate the texture by 90°?  Other than that, it looks good to me

2025-09-15 02:51 UTC, larodriguez22 commented
> Looks great Lau. One small thing, can we use a different texture for the doors, or at least rotate the texture by 90°? Other than that, it looks good to me

I didn't find a better wood texture, so I rotated it 90°

2025-09-15 17:50 UTC, IDavGal approved these changes

2025-09-19 19:23 UTC, francocipollone requested changes
Great job @larodriguez22, it looks much better now! I left some comments PTAL

2025-09-19 19:23 UTC, francocipollone commented on andino_gz/models/office/materials/textures/roof/TCom_Scifi_Panel_512_height.tif
I think this texture is not being used. Remove it if not used

2025-09-19 19:23 UTC, francocipollone commented on andino_gz/models/office/materials/textures/walls/Logo-Final.png
Are we using this ?

2025-09-19 19:23 UTC, francocipollone commented on andino_gz/models/office/materials/textures/walls/logo3.jpg
Are we using this?

2025-09-19 19:23 UTC, francocipollone commented on andino_gz/models/office/model.sdf
> +              <roughness_map>materials/textures/roof/TCom_Scifi_Panel_512_roughness.tif</roughness_map>
We launching the world I see a lot of: 
```
[ign gazebo-1] TIFFFieldWithTag: Internal error, unknown tag 0xa302.
```
errors.

Probably there is some not entirely supported tag within the `tif`s file.

Don't you have a jpg or png variant for these? We can move forward either way but just to be sure

2025-09-29 16:05 UTC, larodriguez22 commented on andino_gz/models/office/model.sdf
> +              <roughness_map>materials/textures/roof/TCom_Scifi_Panel_512_roughness.tif</roughness_map>
The format I found for that texture was in tiff. I did a quick test changing the format to jpg, but it damaged the texture a lot:
<img width="1851" height="1047" alt="image" src="https://github.com/user-attachments/assets/250a8c8f-2d40-4f63-bcc5-cc5237f3d625" />

2025-09-29 16:06 UTC, larodriguez22 commented on andino_gz/models/office/materials/textures/roof/TCom_Scifi_Panel_512_height.tif
Done

2025-09-29 16:07 UTC, larodriguez22 commented on andino_gz/models/office/materials/textures/walls/Logo-Final.png
Done

2025-09-29 16:07 UTC, larodriguez22 commented on andino_gz/models/office/materials/textures/walls/logo3.jpg
Done

2025-09-29 16:07 UTC, larodriguez22 commented on andino_gz/models/office/model.sdf
> +              <roughness_map>materials/textures/roof/TCom_Scifi_Panel_512_roughness.tif</roughness_map>
I could try finding another texture, but it was really hard to find this free one for the tiles

2025-09-30 14:08 UTC, francocipollone commented on andino_gz/models/office/model.sdf
> +              <roughness_map>materials/textures/roof/TCom_Scifi_Panel_512_roughness.tif</roughness_map>
I would just try to convert that tif file to png/jpg and see how it looks (and if there is no more warnings).
If the looks is the same then we can keep those jpg.

2025-09-30 14:09 UTC, francocipollone commented on andino_gz/models/office/model.sdf
> +              <roughness_map>materials/textures/roof/TCom_Scifi_Panel_512_roughness.tif</roughness_map>
@larodriguez22 Just one comment to go!

2025-09-30 16:20 UTC, francocipollone commented on andino_gz/models/office/model.sdf
> +              <roughness_map>materials/textures/roof/TCom_Scifi_Panel_512_roughness.tif</roughness_map>
I pushed [d8f10ec](https://github.com/Ekumen-OS/andino_gz/pull/84/commits/d8f10ec074b88863e67fcb657f30eaf33eab1d57) addressing that. Try it locally and let me know how it looks!

2025-09-30 16:28 UTC, francocipollone approved these changes
LGTM!

2025-09-30 16:30 UTC, merged